import fs from 'fs';
import path from 'path';

/**
 * 实体信息接口
 */
interface EntityInfo {
  className: string;
  properties: Array<{
    name: string;
    type: string;
    isOptional: boolean;
    description: string;
  }>;
  enums: Array<{
    name: string;
    values: string[];
  }>;
}

/**
 * 从实体文件中解析实体信息
 * @param content 实体文件内容
 * @param fileName 文件名
 * @returns 实体信息
 */
function parseEntityFile(content: string, fileName: string): EntityInfo {
  const entityInfo: EntityInfo = {
    className: fileName.replace('.entity.ts', '').replace(/^./, str => str.toUpperCase()),
    properties: [],
    enums: []
  };

  // 提取枚举定义
  const enumRegex = /export enum (\w+) \{([^}]*)\}/g;
  let enumMatch;
  while ((enumMatch = enumRegex.exec(content)) !== null) {
    const enumName = enumMatch[1];
    const enumBody = enumMatch[2];
    const enumValues = enumBody
      .split(',')
      .map(value => value.trim())
      .filter(value => value)
      .map(value => value.split(':')[0].trim());
    
    entityInfo.enums.push({ name: enumName, values: enumValues });
  }

  // 提取属性定义
  const propertyRegex = /\s*@Column\([^)]*\)\s*([a-zA-Z0-9_?]+)\s*:\s*([a-zA-Z0-9_\[\]<>|.]+)\s*;/g;
  let propertyMatch;
  while ((propertyMatch = propertyRegex.exec(content)) !== null) {
    const fullProperty = propertyMatch[1];
    const type = propertyMatch[2];
    const isOptional = fullProperty.endsWith('?');
    const name = isOptional ? fullProperty.slice(0, -1) : fullProperty;
    let description = '';

    // 提取属性上方的注释
    const propertyIndex = propertyMatch.index;
    const commentStart = content.lastIndexOf('/**', propertyIndex);
    
    if (commentStart !== -1) {
      const commentEnd = content.indexOf('*/', commentStart);
      if (commentEnd !== -1) {
        const comment = content.substring(commentStart, commentEnd + 2);
        // 提取注释内容，去除/**和*/
        description = comment
          .replace(/^\/\*\*/, '')
          .replace(/\*\/$/, '')
          .replace(/^\s*\*/gm, '')
          .trim();
      }
    }

    entityInfo.properties.push({ name, type, isOptional, description });
  }

  // 处理关系属性（@ManyToOne, @OneToMany等）
  const relationRegex = /\s*@(ManyToOne|OneToMany|OneToOne|ManyToMany)\([^)]*\)\s*([a-zA-Z0-9_?]+)\s*:\s*([a-zA-Z0-9_\[\]<>|.]+)\s*;/g;
  let relationMatch;
  while ((relationMatch = relationRegex.exec(content)) !== null) {
    const fullProperty = relationMatch[2];
    const type = relationMatch[3];
    const isOptional = fullProperty.endsWith('?');
    const name = isOptional ? fullProperty.slice(0, -1) : fullProperty;
    let description = '';

    // 提取关系上方的注释
    const relationIndex = relationMatch.index;
    const commentStart = content.lastIndexOf('/**', relationIndex);
    
    if (commentStart !== -1) {
      const commentEnd = content.indexOf('*/', commentStart);
      if (commentEnd !== -1) {
        const comment = content.substring(commentStart, commentEnd + 2);
        // 提取注释内容，去除/**和*/
        description = comment
          .replace(/^\/\*\*/, '')
          .replace(/\*\/$/, '')
          .replace(/^\s*\*/gm, '')
          .trim();
      }
    }

    entityInfo.properties.push({ name, type, isOptional, description });
  }

  return entityInfo;
}

/**
 * 生成类型定义文件内容
 * @param entityInfo 实体信息
 * @returns 类型定义文件内容
 */
function generateTypeDefinition(entityInfo: EntityInfo): string {
  const { className, properties, enums } = entityInfo;
  let content = `// 自动生成的类型定义文件，请勿手动修改\n// 基于 ${className}.entity.ts 生成\n\n`;

  // 添加枚举定义
  enums.forEach(enumDef => {
    const prefixedEnumName = `${className}${enumDef.name}`;
    content += `export enum ${prefixedEnumName} {\n`;
    enumDef.values.forEach(value => {
      content += `  ${value},\n`;
    });
    content += `}\n\n`;
  });

  // 添加类型定义
  content += `export type ${className}Type = {\n`;
  properties.forEach(prop => {
    if (prop.description) {
      // 确保注释格式正确
      const formattedDescription = prop.description.split('\n')
        .map(line => `   * ${line.trim()}`)
        .join('\n');
      content += `  /**\n${formattedDescription}\n   */\n`;
    }
    // 处理类型可能与枚举冲突的情况
    let propType = prop.type;
    enums.forEach(enumDef => {
      if (propType === enumDef.name) {
        propType = `${className}${enumDef.name}`;
      }
    });
    content += `  ${prop.name}${prop.isOptional ? '?' : ''}: ${propType};\n`;
  });
  content += `}\n\n`;

  // 添加创建类型（排除自增和自动生成的字段）
  const autoGeneratedFields = ['id', 'createdAt', 'updatedAt', 'deletedAt'];
  const createProperties = properties.filter(
    prop => !autoGeneratedFields.includes(prop.name)
  );

  content += `export type ${className}CreateType = {\n`;
  createProperties.forEach(prop => {
    if (prop.description) {
      // 确保注释格式正确
      const formattedDescription = prop.description.split('\n')
        .map(line => `   * ${line.trim()}`)
        .join('\n');
      content += `  /**\n${formattedDescription}\n   */\n`;
    }
    // 处理类型可能与枚举冲突的情况
    let propType = prop.type;
    enums.forEach(enumDef => {
      if (propType === enumDef.name) {
        propType = `${className}${enumDef.name}`;
      }
    });
    content += `  ${prop.name}${prop.isOptional ? '?' : ''}: ${propType};\n`;
  });
  content += `}\n\n`;

  // 添加更新类型（所有字段可选）
  content += `export type ${className}UpdateType = {\n`;
  properties.forEach(prop => {
    if (prop.description) {
      // 确保注释格式正确
      const formattedDescription = prop.description.split('\n')
        .map(line => `   * ${line.trim()}`)
        .join('\n');
      content += `  /**\n${formattedDescription}\n   */\n`;
    }
    // 处理类型可能与枚举冲突的情况
    let propType = prop.type;
    enums.forEach(enumDef => {
      if (propType === enumDef.name) {
        propType = `${className}${enumDef.name}`;
      }
    });
    content += `  ${prop.name}?: ${propType};\n`;
  });
  content += `}\n`;

  return content;
}

/**
 * 主函数
 */
function main() {
  const entitiesDir = path.join(__dirname, '../src/entities');
  const typesDir = path.join(__dirname, '../types');

  // 确保types目录存在
  if (!fs.existsSync(typesDir)) {
    fs.mkdirSync(typesDir, { recursive: true });
  }

  // 读取所有实体文件
  const entityFiles = fs
    .readdirSync(entitiesDir)
    .filter(file => file.endsWith('.entity.ts'));

  console.log(`找到 ${entityFiles.length} 个实体文件`);

  // 处理每个实体文件
  entityFiles.forEach(file => {
    const filePath = path.join(entitiesDir, file);
    const content = fs.readFileSync(filePath, 'utf8');
    
    try {
      const entityInfo = parseEntityFile(content, file);
      const typeContent = generateTypeDefinition(entityInfo);
      
      // 写入类型定义文件
      const typeFileName = `${entityInfo.className}.types.ts`;
      const typeFilePath = path.join(typesDir, typeFileName);
      
      fs.writeFileSync(typeFilePath, typeContent, 'utf8');
      console.log(`✅ 生成类型文件: ${typeFileName}`);
    } catch (error) {
      console.error(`❌ 处理文件 ${file} 时出错:`, error);
    }
  });

  console.log('\n🎉 所有类型文件已生成完毕！');
}

// 执行主函数
main();
